### ISSUE TITLE
Odd effects caused by passing Dice instances in constructor.

### ISSUE THREAD

**Issue by MrBenGriffin** [Level-2/Dice#114]
(We are aware of the similarities with issue  #99  and I have commented there also - the proposed solution seems not to work for shared instances of Dice. Hence this issue).

I'm not going to say that the practice is good or necessary, but we were looking at passing over a shared service container as a constructor parameter and we ran into trouble.  After quite some time of trying to work out what was going on, I decided to post it as an issue. 

It looks like we are doing something wrong (programmatically, rather than strategically) and would like some guidance about if it is (a) possible to do what we wish, or (b) it should be possible or (c) it should be documented as not possible or (d) something else altogether... :-D

```php
<?php

mb_internal_encoding('UTF-8');
spl_autoload_register();
require 'vendor/autoload.php';

$s = new Dice\Dice();

//The following 2 rules were added as an attempt to get TestB constructor to work.
$s->addRule("*", [
		"constructParams" => [
			Dice\Dice::class => function () use ($s) {
				return $s;
			}
		],
		"substitutions"   => [
			Dice\Dice::class => [
				"shared" => true,
				"shareInstances" => true,
				"instance" => function () use ($s) { //this = proposed answer to issue 99
					return $s;
				}
			]
		]
	]
);

$s->addRule(Dice\Dice::class,["shared" => true,"constructParams" => [$s]);
//We don't believe that all the above should be necessary.
//We have tried with all the combinations that made sense to us.

//This rule is to get the LoggerInterface to work, deliberately using a closure.
$s->addRule('*', [
	'substitutions' => [
		Psr\Log\LoggerInterface::class => [
			'instance' => function () {
				return new \Monolog\Logger("Log");
			}
		]
	]
]);

//This is the sort of constructor we want to avoid..
class TestA {
	public function __construct(\Psr\Log\LoggerInterface $log) {
		$this->log = $log;
		print_r($this->log);
	}
}

//This is the sort of constructor we want to implement.
class TestB {
	public function __construct(\Dice\Dice $s) {
		$this->log = $s->create(\Psr\Log\LoggerInterface::class);
		print_r($this->log);
	}
}

$uriA = $s->create('TestA');
//This works fine.

$uriB = $s->create('TestB');
// Fatal error: Uncaught Error: Cannot instantiate interface
// Psr\Log\LoggerInterface in /Library/WebServer/NView/vendor/level-2/dice/Dice.php on line 70
// ** The reason is that the Dice instance at line 38 no longer has the LoggerInterface rule.

```

**Comment by TomBZombie** [comment]
The problem here is this line:

```php
        $this->log = $s->create(\Psr\Log\LoggerInterface::class);
```

This will try to create an instance of  `LoggerInterface`. You should create a named instance to store the logger instance:

```php
$s->addRule('$Logger', [
    'instanceOf' => \Monolog\Logger::class,
    'constructParams' => ['log']
]);

```

Then in `TestB::__construct`:

```php
        $this->log = $s->create('$Logger');
```

**Comment by MrBenGriffin** [comment]
@TomBZombie , thanks - but I am still confused. It feels you have provided a work-around.
Why doesn't the substitution rule for Psr\Log\LoggerInterface => Monolog\Logger not kick in for TestB, while it does for TestA?

**Comment by TomBZombie** [comment]
The reason for this is that `substitution` rules only apply to a specific class constructor. `*` does mean "the constructor of any class" but when you use `$s->create(\Psr\Log\LoggerInterface::class);` no class constructor is being invoked to run the substitution rules.

Essentially substitutions like this:

```php
$dice->addRule('X',  ['substitutions' => ['Y' => 'Z'] ] );
```

- When class `X` 's constructor is invoked find the argument that is hinted as `Y` and replace it with an instance of `Z`. 

With:

```php
$dice->addRule('*', ['substitutions' => ['Psr\Log\LoggerInterface' => 'Monolog\Logger']] );
```

The only constructor that is called is `Monolog\Logger::__construct` none of the arguments are hinted as `Psr\Log\LoggerInterface` so the substitution is not made. Essentially substitutions only affects constructor arguments and not explicit `$dice->create()` calls.

You could name your instance `\Psr\Log\LoggerInterface` to achieve this:

```php
$s->addRule(\Psr\Log\LoggerInterface::class, [
    'instanceOf' => \Monolog\Logger::class,
    'constructParams' => ['log']
]);

$log = $s->create(\Psr\Logger\Log::class);

echo get_class($log);
```

**Comment by MrBenGriffin** [comment]
@TomBZombie, ah, okay. Thanks.
So the reason why we chose to use a substitutions method was in order to be able to declare a closure, such that we could return a specific (shared) instance of a class or similar.  

We weren't aware that substitutions were only affecting constructors and not create(). 

Regarding the issue of passing dice as a parameter, we have decided (while dealing with safe migration of legacy code where there are heavy dependencies on existing constructors) not to pass the Dice instance at all to constructors, and instead use a global static. 

However, I think that we were hoping to declare closures on 'instanceOf' rules, in order to dynamically affect the results of class requests.

**Comment by TomBZombie** [comment]
> Regarding the issue of passing dice as a parameter, we have decided (while dealing with safe migration of legacy code where there are heavy dependencies on existing constructors) not to pass the Dice instance at all to constructors, and instead use a global static.

If you're having to change the constructor to include `$dice` and you have `new Class(...)` throughout the code, then yes you'll struggle to make the change in a simple manner because you'll need to make the `$dice` instance available wherever `new` is used. That said, you shouldn't have too much trouble injecting it as above.

In most cases  you should be able to refactor out `new` calls entirely by injecting the fully constructed object. If you're changing the constructor to include a `$dice` reference then you may as well just change it to include the dependency :)

The only place you'll run into trouble is where you have things like

```php

$x = $foo + $bar;

$obj = new SomeClass($x);
```

Because there is no simple way to calculate X inside the container. In these cases you will need to pass in a Dice instance or a factory.

> However, I think that we were hoping to declare closures on 'instanceOf' rules, in order to dynamically affect the results of class requests.

You should be able to use the code I pasted above ( https://github.com/Level-2/Dice/issues/114#issuecomment-228113571 ) to globally replace interfaces with concrete classes.

**Comment by MrBenGriffin** [comment]
Tom, thanks. I think we wanted to do things with Dice that it doesn't really do. 
Most of your suggestions are what we came up with too - but we were curious about why the code above was failing.

Is there a reason why you designed substitution rules to onlly apply to a specific class constructor?
It seems a bit undocumented and, though there may be an excellent reason for it, rather confusing - as in most other cases one can use ->create() in a manner similar to invocation via a class constructor.

Would it not make sense to unify create() so that it mirrors the same effects of invocation via a class constructor?  I understand that there are other methods of handling polymorpsim around the create() scope (such as using a variable), and that one can use InstanceOf for simple interface implementation work.

One of the things that we were hoping for (iirc) was the ablity to install a pre-existing instance into dice 
```php
- eg $foo = new ComplexClass(); // instance is unknown to dice...
  $dice->addRule("ComplexInterface",["shared"=>true,"useInstance"=>$foo]); 
//we attempted to do something like this with a closure, but that means (as above) that we cannot do
[...] $cc = $dice->create("ComplexInterface");
```

Anyhow, maybe we are just very confused... :-D 
Thanks for taking the time to explain stuff to us, btw.

**Comment by TomBZombie** [comment]
> Is there a reason why you designed substitution rules to onlly apply to a specific class constructor?

Because it's more flexible. Substitution rules are generally applied to specific classes so "When an instance of class Foo is created, supply an instance of class Bar where Baz is hinted". This can't be applied to `Create` because here because you're creating the *dependency* without the scope of the constructor it's being injected into.

With significant changes it would be possible to make this work, but:

1. There are enough methods of achieving the same thing that it's not worth changing the behaviour
2. Dice is a *Dependency Injection Container* not a *Service Locator*, it handles injection of dependencies to the class supplied in `create` and returns a constructed instance of that class, it doesn't locate named services (although you can use it like this, it's not really what it's designed to do)
3. Calling `create` throughout the application is generally bad practice. Ideally you'd have as few calls to `create`as possible throughout the application to avoid coupling the application to the container. In an ideal world you should be able to replace Dice with another container by changing a single point in the code.

> One of the things that we were hoping for (iirc) was the ablity to install a pre-existing instance into dice


Currently there's not a way to do this, however what's wrong with configuring the instance inside Dice?

```php
 $dice->addRule("ComplexInterface",["shared"=>true,"instanceOf"=>"ComplexClass",
"constructParms" => ['...']
]); 
```

**Comment by garrettw** [comment]
Tom, in order to install an existing instance into Dice, could they not set up a rule for a named instance that does a substitution using either the variable holding the object, or an anonymous function that returns it?
(Not that I'm necessarily recommending it as the optimal solution, of course.)

**Comment by TomBZombie** [comment]
Yes, that was one of the options given in the linked issue, however it doesn't affect direct `$dice->create()` calls.

**Comment by garrettw** [comment]
Sorry, I meant `instanceOf`, not substitution
