### ISSUE TITLE
Passing instance of created class to subclasses

### ISSUE THREAD

**Issue by iBrazilian2** [Level-2/Dice#160]
This may end up being a stupid question, as I've read a lot on the documentation, but I am a bit lost.

I've created an instance of Dice in the \Core\Controller class which has some method as helpers, and added a PDO rule (connection) and made it available that to every controller construct, currently it's just for PDO.

```
use \path\models\users;
Class Planner extends \Core\Controller {
	public function __construct(){
		$this->user_id = $_SERVER['HTTP_USERID'];
		$this->model_users = $this->injection->create(users::class, [$this->user_id]);
		
		$this->generator = new Generator($user_id);
	}

	public function runAction(){
		// method accessible via i.e https://url/v1/planner/run
	}
}
```

The generator class requires making calls to queries from the users class too, recreating a new connection to the users class, which is instantiated in it's constructor.

```
use \path\models\users;
Class Generator {
	public function __construct(){
		$this->usersModel = new Users($user_id);
	}
	
	public function create_menu(){
		// here I fetch some data from the users model and do stuff...
	}
}
```

I can't "use \Dice\Dice" in the Generator class to just fetch the already instantiated container because as far as I understood, dice doesn't have a setter method.

I read about inheritance in the dice documentation, not sure if it's the 12+ hours of trying and figuring things out to get this to work but I just couldn't undertand how to. I could technically pass the $this->model_users object reference to the generator construct, in the Planner class construct where I instantiated it, but then what's the reason for a DI container.

**Comment by TRPB** [comment]
I'm afraid I don't fully understand your question. Can you provide an example of what you're trying to do without using a container?

You shouldn't, however, be instantiating dependencies in a constructor, see this article: http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/

Nor, should you really, be referencing the container in your controller.

What you should be doing is probably this:

```php

use \path\models\users;
Class Generator {
	public function __construct(Users $users){
		$this->usersModel = $users;
	}
	
	public function create_menu(){
		// here I fetch some data from the users model and do stuff...
	}
}

```


and


```php
use \path\models\users;
Class Planner extends \Core\Controller {
	public function __construct(Generator $generator){
		$this->generator = $generator;
	}

	public function runAction(){
		// method accessible via i.e https://url/v1/planner/run
	}
}

```


Then use Dice to instantiate the entire object graph. The idea of dependency injection relies on a concept called *inversion of control* where objects are given the dependencies they need rather than creating them for themselves.

Given the code above you could use Dice to construct all the objects:

```php
$dice = $dice->addRule('Users', [
	'constructParams' => [
		$_SERVER['HTTP_USERID']
	]
]);

$planner = $dice->create('Planner');
```

If you're not using inversion of control, you end up passing the DI container around the application and constructing objects everywhere.

> but then what's the reason for a DI container.

Imagine you had `new Users($user_id)`  in a dozen places in your application. The requirements change so that the constructor now requires a `Authentication` instance: `new Users(new Authentication, $user_id)`. You'd need to find every occurrence of `new Users` and change it. With a DIC that change happens in one location, with Dice you don't ever need to change anything because it works out the dependency for you.
