### ISSUE TITLE
addRules creates returns another Dice instance

### ISSUE THREAD

**Issue by vasikgreif** [Level-2/Dice#169]
I was struggling with adding rules to my container, after dicing into Dice code I found out that `addRules` returns a cloned instance of Dice:

```php
public function addRules($rules): self {
		if (is_string($rules)) $rules = json_decode(file_get_contents($rules), true);
		$dice = clone $this;
		foreach ($rules as $name => $rule) $this->addRuleTo($dice,$name, $rule);
		return $dice;
	}
```

Is this correct and expected behaviour? If so, it would make sense to add that to the docs.

**Comment by garrettw** [comment]
Yes, that is the expected behavior. It was implemented to introduce immutability (see #148).

**Comment by vasikgreif** [comment]
Thanks for the clarification. I think it would make sense to say this in the docs, as the following did obviously not work:

```
$container = new Dice();
$container->addRules(
			[
				'Admin' => [ 'shared' => true ],
			]
		);

```

**Comment by TRPB** [comment]
Yes, this is the intentional behaviour. An immutable class isn't prone to action-at-distance.

(1)
```php
//assume $dice in current scope
doSomethingWithDice($dice);
$dice->create('Foo');
```

(2)
```php
//assume $dice in current scope
//     doSomethingWithDice($dice);
$dice->create('Foo');
```

Without immutability there is no way to know whether the code in `(1)` and `(2)` have the same result. Should commenting out that line have an effect on how the following line is executed? What if during development something inside the `doSomethingWithDice()` call stack, the dice instance has the `Foo` rule overwritten? This would introduce a bug.

Instead, with immutability you have to explicitly indicate that a change in the instance is expected:

```php
$dice = doSomethingWithDice($dice);
```

The documentation shows this behaviour however, I'll will update it to explain the reasoning behind it.
