### ISSUE TITLE
[RFC] PSR-2

### ISSUE THREAD

**Issue by praswicaksono** [Level-2/Dice#60]
I think its better to improve code readability by following PSR-2 coding convention. I would love to send PR on this issue

**Comment by garrettw** [comment]
Good luck. I think he prides himself on how few lines of code it is.

**Comment by TomBZombie** [comment]
Feel free to run the code through a formatter :) Alternatively, @garrettw has a fork with alternative formatting.

**Comment by garrettw** [comment]
... which I will be updating to be more PSR-2 compliant.

**Comment by msheakoski** [comment]
Everyone is free to format their code however they wish. One thing to take note of: if you want to accept patches and contributions to your project and have a community, it is much easier to work with code that is not highly compressed and somewhat standardized. Just because a project is public doesn't mean that's the goal though; maybe the author is just sharing a creation with the world the same way that an artist shares a painting.

**Comment by TomBZombie** [comment]
That's a fair enough point. I'm not a fan of PSR-2 (the bracket on next vs same line debate is neverending but PSR-2s inconsistency on the subject is particularly irksome) but I will format and comment the code a bit better.

**Comment by msheakoski** [comment]
I didn't like it at first either. These days, I don't really care one way or the other. I just run it through the code reformatter in IntelliJ IDEA and move on to the next thing. PSR-2 or whatever format you use isn't as important as being consistent throughout the project.

**Comment by garrettw** [comment]
>PSR-2s inconsistency on the subject is particularly irksome
Oh? I wasn't aware of an inconsistency -- guess I should look into that.
But what I've started doing is just running the code through php-cs-fixer using default settings.

>whatever format you use isn't as important as being consistent throughout the project
Very true.
Personally, I've grown to like having braces/brackets on their own line as the extra whitespace does seem less visually cluttered and easier to read at a glance.

**Comment by TomBZombie** [comment]
> Oh? I wasn't aware of an inconsistency -- guess I should look into that. 

It uses braces on the next line for methods and braces on the same line for if/while statements. I'd never seen anyone do this until PSR-2.

**Comment by garrettw** [comment]
Oh interesting. I have come to really like that way. To me, it emphasizes the importance and separate-ness of structural things like classes and methods over mere flow control; everything is procedural within a method, but when viewed from the perspective of an entire class, each method is kind of like its own document.

**Comment by TomBZombie** [comment]
I've added comments so the code is a lot clearer. I'm reluctant to use PSR-2 simply because I find it makes the code more difficult to read (subjectively of course).

Braces in if statements are redundant, and in fact I'd go as far as to agree with Robert C. Martin in clean code who said something along the lines of (I'm paraphrasing here) 'an if statement should be followed by a single other statement, ideally a function call or variable association'. Sometimes this is not possible of course. He also mentions vertical space with a nice example of how unnecessary comments actually make the code less readable. I'll see if I can dig out my copy and get an exact quote.

For Dice specifically, it would be nicer to break the functions apart but I'd prefer to keep high benchmark scores at the expense of clarity. For example, all the code in `foreach ($paramInfo...` should really be in its own method, but the added function call gives little practical benefit at the expense of a performance overhead.

**Comment by msheakoski** [comment]
@TomBZombie: I think your changes help a great deal to make the code more understandable. Since you're inlining a lot of code to keep performance high, the many comments help to keep the reader on the path and explain _why_ things are being done. I really like the new array-based configuration vs Rule object btw, it feels very clean and consistent.

**Comment by Nemoden** [comment]
https://github.com/Level-2/Dice/pull/108
