### ISSUE TITLE
how to configure rule globally

### ISSUE THREAD

**Issue by roji430** [Level-2/Dice#94]
I am new to Dice..i have few question to ask..
1.By reading your documentation on https://r.je/dice.html.. the rules are created before the create function is invoked...my question is ,is it necessary to create rules every time i need the class object?
2.in singleton pattern an object of specific class can be returned using something like 
 \Application\Core\Request::getInstance(). how i get the same object using Dice?
3.is it possible to create rules of a class globally ? how? please give me some examples..
4.Argument Unpacking is available only in php 5.6 .
how i perform this code in 5.3 am working on it
$class->name(...$params($args, $share)); 
5.Following functions are not found in file
a.allowsNull();
b.isVariadic()
c.isDefaultValueAvailable()
d.getDefaultValue()
finally if u feel my question are very simple...please not feel bad..i new to dice also in learning stage of php OOP,MVC ..if necessary please contact me through my email
email : roji430@gmail.com...

**Comment by roji430** [comment]
please replay as possible

**Comment by TomBZombie** [comment]
Hi roji430:

Firstly PHP5.3 has not been supported by PHP for two years (see http://php.net/supported-versions.php ) as such, your server is open to several security vulnerabilities and bugs and you should upgrade to at least 5.5 (Which is the oldest version currently supported) ASAP.

Because 5.3 is unsupported by PHP it is not supported by most projects, such as Dice. Dice has a branch for PHP5.4-PHP5.5 if you are unable to use PHP5.6.


> 1.By reading your documentation on https://r.je/dice.html.. the rules are created before the create function is invoked...my question is ,is it necessary to create rules every time i need the class object?

After you've assigned a rule to Dice you can create as many instances of that class as you like without assigning the rule again:


```php
$dice->addRule('PDO',  [
       'constructParams' => ['mysql:host=127.0.0.1;dbname=mydb', 'username', 'password'] 
        ]);


$pdo1 = $dice->create('PDO');
$pdo2 = $dice->create('PDO');

```

This will create two instances of PDO both following the applied rule.

> 2.in singleton pattern an object of specific class can be returned using something like 
\Application\Core\Request::getInstance(). how i get the same object using Dice?

In short, don't: 

http://misko.hevery.com/2008/08/17/singletons-are-pathological-liars/
http://brollace.blogspot.co.uk/2013/04/why-singletons-are-bad-patterns.html
http://blogs.msdn.com/b/scottdensmore/archive/2004/05/25/140827.aspx 
http://williamdurand.fr/2013/07/30/from-stupid-to-solid-code/
http://smart421.wordpress.com/2011/08/31/why-helper-singletons-and-utility-classes-are-mostly-bad-2/ 
http://misko.hevery.com/code-reviewers-guide/flaw-brittle-global-state-singletons/

If you really need to do this, you can use a substitution:

```php
$rule = [
        'substitutions' => ['Foo' => function() { 
                  return Foo::getInstance();
         }]
];


```

Which will call `Foo::getInstance()` to supply the argument hinted with `Foo`

> 3.is it possible to create rules of a class globally ? how? please give me some examples.

See https://r.je/dice.html#example2

**Comment by roji430** [comment]
thank you for the fast replay and for the information .. get back you  soon if i have issues(problems/Doubts).

**Comment by roji430** [comment]
What about the missing functions?

**Comment by TomBZombie** [comment]
I don't really know what you're trying to ask.

**Comment by roji430** [comment]
in Dice.php file there is no function definition for following
a.allowsNull();
b.isVariadic()
c.isDefaultValueAvailable()
d.getDefaultValue()

**Comment by TomBZombie** [comment]
These functions are part of PHP's reflection library and as such exist in PHP itself

**Comment by roji430** [comment]
ok fine.. thank you

**Comment by roji430** [comment]
dice addRule not adding rule
<code>$dice=new \Dice\Dice();
$rule=['shared' => true];
$dice->addRule('\\XYZ\\Abc' ,$rule);

</code>
but not adding the rule i tested by creating two instance..
