### ISSUE TITLE
Dice rule object and dice instance object creation 

### ISSUE THREAD

**Issue by roji430** [Level-2/Dice#96]
how to create dice rule object and dice instance object .
where is those classes? @TomBZombie

**Comment by TomBZombie** [comment]
These were classes available in Dice 1.0 and have since been removed. Please upgrade to 2.0 and follow the docs.

**Comment by roji430** [comment]
How to write MVC router with dice 2 .. Using a Dependency Injection Container to simplify Routing in an MVC framework..code for the dice part..

**Comment by guigouz** [comment]
@roji430 I integrated Dice to resolve controller dependencies on my url router, you can check the code at https://github.com/objectiveweb/router

**Comment by dustingraham** [comment]
@TomBZombie The instructions on the main page say to use \Dice\Instance https://github.com/Level-2/Dice Might move that into a changelog rather than the readme. Pretty common to scroll through the readme quickly looking for code examples. I was also digging through the source looking for \Dice\Instance
