### ISSUE TITLE
Can Dice inject intself into a class?

### ISSUE THREAD

**Issue by mbn18** [Level-2/Dice#99]
Hi,

I have a factory with the following signature:

```php
class MapperFactory
{
    public function __construct(Dice $di);
}
```

And this is how I init it.

```php
$di = new Dice();
$di->create(MapperFactory::class);
```

Can I tell Dice to inject itself into the MapperFactory instead of creating a new Dice?
I tried passing share rule but that didn't helped.

Thanks

**Comment by TomBZombie** [comment]
To do this you'll need to provide the `$dice` instance as a substution:

```php
$di = new Dice();
$d->addRule(MapperFactory::class, [
'substitutions' => ['\\Dice\\Dice' => function() use ($di) {
     return $di;
} 
]);
$di->create(MapperFactory::class);
```

This will use the constructed `$di` instance as a substitution instead of creating a new `Dice` instance.

You will need to change your MapperFactory class to account for the namespace either using:

```php
class MapperFactory
{
    public function __construct(\Dice\Dice $di);
}
```

or

```php
use \Dice\Dice;
class MapperFactory
{
    public function __construct(Dice $di);
}
```

**Comment by garrettw** [comment]
That said, it's probably not a great idea to pass Dice around like that. What else are you doing in your `MapperFactory` that requires an instance of Dice to be injected?
(If we can improve your code while you're here, then all the better! And maybe others would benefit from seeing it as well.)

**Comment by TomBZombie** [comment]
It's not necessarily a bad thing to pass a DI container into a factory, however, the DI container might be able to replace the container entirely.

**Comment by mbn18** [comment]
@TomBZombie ,Thanks for the tip and this great class.

@garrettw , The factory will be used by a unit of work pattern to persist unclean entities. So it need the ability to fetch mappers that are derived from the entity type.

**Comment by mbn18** [comment]
The following error is returned by the code bellow. Any idea?
> TypeError: Argument 1 passed to Some\Path\MapperFactory::__construct() must be an instance of Dice\Dice, instance of Closure given, called in /srv/httpd/project/vendor/level-2/dice/Dice.php on line 66

```php
$di = new Dice();
$rule = [
    'substitutions' => [
        Dice::class => function () use ($di) : Dice {
            return $di;
        }
    ]
];
$di->addRule(MapperFactory::class, $rule);
$this->di->create(MapperFactory::class);
```

The requested class:
```php
use Dice\Dice;

class MapperFactory
{
    public function __construct(Dice $di);
}
```
Any idea what is wrong?

**Comment by TomBZombie** [comment]
Apoligies, the code should have been:

```php

$di = new Dice();
$rule = [
    'substitutions' => [
        Dice::class => ['instance' => function () use ($di) : Dice {
            return $di;
        }]
    ]
];
$di->addRule(MapperFactory::class, $rule);
$this->di->create(MapperFactory::class);

```

The syntax I posted above used to work but was changed as it made it impossible to pass closures as actual substitutions.

**Comment by mbn18** [comment]
Work wonderfully. Thanks again.

**Comment by solleer** [comment]
Is there a way to set up passing the dice instance using json config

**Comment by TomBZombie** [comment]
Generally, passing in the Dice instance is poor design and there's currently no way to do this using JSON, you'll need to do it as above.

However, it's more likely you'll need a new dice instance with its own set of rules in a factory, for this you can use:

```php
{
  "MyFactory": {
       "substitutions": {"\\Dice\\Dice": {"instance": ["\\Dice\\Loader\\Json", "load"], "params": ["config.json"]}
   }
}  

```

Which will create a new instance with its own ruleset.

**Comment by solleer** [comment]
The problem is when I need to configure the router with rule objects that use dice

**Comment by TomBZombie** [comment]
In instances like this i would expect the objects created by the router to have an entirely different set of dependencies to the framework's initialisation code. It would be possible to make the Json loader add a $this instance to the Dice object but it's going to be better design to give a different dice instance to your router with a specific configuration

**Comment by MrBenGriffin** [comment]
Also cf. issue 114. We were referring to this issue too, and could not decide if you were answering the same problem.  
@TomBZombie, you say "Generally, passing in the Dice instance is poor design" -  we have been discussing this, and came to the conclusion that _iideally_ one would only have a single 'create' across the application and then pass all dependencies over the constructor, which would mean that the class itself doesn't "need to know" about the existence of an IoC.  

However, when migrating existing code over to an IoC, where many concrete dependencies are invoked in the class methods (and their sub-classes) rather than the class constructor, it seems fair to argue that passing in an IoC instance to the (base class) constructor is a reasonable migration approach as a stepping stone towards refactoring a dependency-free class. This is mostly the case where (and I'm talking about my own poor practice, having been a hacker/coder for far too long) one has complex classes with multiple dependencies, and one wishes to separate implementation logic from business logic. 

On the other hand, and in light of the difficulties we have had passing a shared Dice instance over in the constructor, we are opting for a global / static instance of Dice as our halfway house - so that we can replace e.g. "$logger = new XYZLogger()" in our methods with "$this->logger = Global::$dice->create("LoggerInterface") in our constructor.  
We are loathe to rewrite all our constructors on existing projects, due to the cost of re-writing each instantiation.  However, new classes will pass their dependencies over as arguments in the constructor.
